---
title: "Arm"
author: "Ana Palacio-Castro"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    fig_height: 8
    fig_width: 8
    df_print: paged
    toc: yes
    toc_float: true
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
  knitr::opts_chunk$set(warning = FALSE, 
                        message = FALSE,
                        #options(knitr.kable.NA = ''),
                        fig.align = "center")
```

# Libraries and settings

```{r, include=FALSE}
# Libraries
    library(plyr)
    library(tidyverse)
    library(reshape2)
    library(lubridate)
    library(knitr)
    library(dplyr)
    library(broom)

    library(ggpubr)
    library(ggthemes)
    library(gridExtra)
    library(ggExtra)
    
#Models     
    library(lmerTest)
    library(emmeans)


# Plots
MyTheme<-theme_bw() +  
theme(legend.position="top",
          plot.background=element_blank(),
          #axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          legend.title = element_blank(),
          panel.background =element_rect(fill = NA, 
                                         color = "black"))
  #guides(fill=guide_legend(nrow=2,byrow=TRUE), shape=guide_legend(nrow=3,byrow=TRUE))
```

# Import and format data

```{r}
Import_Arm<- function (dir)  {
  
# 1. Read all the .csv files (; delimited) and consolidate them in a single data frame
  # dir: folder containing the .csv files. The data in the dir can be separated in subfolders, 
  # recursive = TRUE will find the .csv files inside the subfolders
  # You can use the subfolders names to later extract information with the option full.names=TRUE
  
  Arm.data<-plyr::ldply (list.files(path=dir, pattern="*.csv", 
                                full.names=TRUE, recursive = TRUE),
                     function(filename) {
                       dum=(read.csv(filename, sep = ",", blank.lines.skip=T))
                       dum$filename=filename
                       return(dum)
                     })
}

Duration<-Import_Arm("Data")


Duration_name <- plyr::rbind.fill(lapply(strsplit(as.character(Duration$filename), split="/"), 
                                    function(X) data.frame(t(X))))

Duration$created_at[] <- lapply(Duration$created_at, 
                                gsub, pattern="-04:00", replacement="")
Duration$created_at[] <- lapply(Duration$created_at, gsub, pattern="T", 
                                replacement=" ")

# Date_time <- plyr::rbind.fill(lapply(strsplit(as.character(Duration$created_at), split="T"), 
#                                     function(X) data.frame(t(X))))

Duration <- cbind(Duration_name[,-1], Duration[,-10])

head(Duration)
colnames(Duration) <- c("Arm", "File", "DateTime", "entry_id", "beaker", "duration", "errors", "latitude",  "longitude",  "elevation", "status")

# Remove duplicate rows
Duration$ID<-paste0(Duration$Arm, Duration$DateTime)
Duration <- Duration[!duplicated(Duration$ID), ]
#Duration<-Duration[!(Duration$duration<3),]
```


```{r, include=FALSE}

Duration$Arm<-as.factor(Duration$Arm)
Duration$beaker<-as.factor(Duration$beaker)
Duration$DateTime<-as.character(Duration$DateTime)
Duration$Date<-as.Date(Duration$DateTime)
Duration$Date_Time<-as.POSIXct(Duration$DateTime)

summary(Duration)
```

# Current data

```{r}
Experiement<-Duration[Duration$Date>"2023-05-01", ]
Nutrients<-Experiement[Experiement$Date<"2023-05-18", ]
Disease1<-Experiement[Experiement$Date>"2023-05-18", ]
Disease1<-Disease1[Disease1$Date<"2023-05-20", ]
Disease2<-Experiement[Experiement$Date>"2023-05-19", ]

```

```{r}
N.Armand<-Nutrients[Nutrients$Arm=="Armand", ] %>% count(beaker, 
                                  sort = F)

N.Armanda<-Nutrients[Nutrients$Arm=="Armanda", ] %>% count(beaker,
                                  sort = F)
D.Armand<-Disease2[Disease2$Arm=="Armand", ] %>% count(beaker, 
                                  sort = F)

D.Armanda<-Disease2[Disease2$Arm=="Armanda", ] %>% count(beaker,
                                  sort = F)

Doses<-cbind(N.Armand, N.Armanda[,-1 ], D.Armand[,-1], D.Armanda[,-1 ])
colnames(Doses) <-c("Beaker", "Armand_Nut", "Armanda_Nut", 
                          "Armand_Dis", "Armanda_Dis")

kable(as.data.frame(Doses, format = "markdown"), 
      longtable = TRUE)
```

# Nutrients
```{r}
Minutes_nutrients<- ggplot(Nutrients, aes(beaker, duration, fill=Arm)) + 
  
  MyTheme +
  scale_fill_brewer(palette = "Dark2")+
  scale_colour_brewer(palette = "Dark2")+
  scale_y_continuous(limits = c(20, 85),
                      expand = c(0.01, 0.01),
                      breaks = seq(0, 100, 10),
                      name="Seconds per beaker")+
   # scale_x_continuous(limits = c(0, 24),
  #                     expand = c(0.01, 0.01),
  #                     breaks = seq(0, 24, 2),
  #                     name="Time of the day")+
  geom_jitter(aes(colour=Arm), size=1, alpha=0.3)+
  stat_summary(fun.data = "mean_cl_boot", aes(fill=Arm), shape=21)
  # annotate(geom="text", x = 12, y = 1, parse=TRUE,
  #              label =paste0("Armand (min) ",mean.round$round.min[1], size=4))+
  #  annotate(geom="text", x = 36, y = 1, parse=TRUE,
  #              label =paste0("Armanda (min) ",mean.round$round.min[2], size=4))

Minutes_nutrients + facet_wrap(~Date)
#Minutes_nutrients

Minutes_nutrientsb<- ggplot(Nutrients, aes(Arm, duration, fill=Arm)) + 
  MyTheme +
  scale_fill_brewer(palette = "Dark2")+
  
  scale_y_continuous(limits = c(20, 85),
                      expand = c(0.01, 0.01),
                      breaks = seq(0, 100, 10),
                      name="Mean beaker duration (s)")+
  
  stat_summary(fun.data = "mean_cl_boot", aes(fill=Arm), shape=21)
  # annotate(geom="text", x = 1, y = 28, parse=TRUE,
  #               label = as.character(mean.round$round.min[1]), size=4)+
  # annotate(geom="text", x = 2, y = 28, parse=TRUE,
  #            label = as.character(mean.round$round.min[2]), size=4)
#Minutes_nutrients + facet_wrap(~Date)
#Minutes_nutrientsb
```


```{r, echo=FALSE}
mean.beaker <- ddply (Nutrients, .(beaker, Arm, Date), summarise,
                D_mean = mean (duration, na.rm = T),
                D_sd = sd (duration, na.rm = T),
                number = n())
mean.beaker

mean.Arm <- ddply (Nutrients, .(beaker, Arm),summarise,
                D_mean = mean (duration, na.rm = T),
                D_sd = sd (duration, na.rm = T),
                number = n())
mean.Arm

mean.day <- ddply (Nutrients, .(Date, Arm),summarise,
                D_mean = mean (duration, na.rm = T),
                D_sd = sd (duration, na.rm = T),
                number = n())
mean.day

mean.round <- ddply (mean.Arm, .(Arm),summarise,
                R_mean = mean (D_mean, na.rm = T),
                #R_sd = sd (D_mean, na.rm = T),
                number = n())

mean.round$round.min<-(round((mean.round$R_mean*mean.round$number)/60, 2))
mean.round$DoseDay<-(24*60)/mean.round$round.min
mean.round$Vol.SW.day.mL<-mean.round$DoseDay*60
mean.round$Changes.SW.day.mL<-mean.round$Vol.SW.day.mL/600
mean.round$umol.NH.day.mL<-mean.round$DoseDay*0.3
mean.round$uM.NH.day.mL<-mean.round$DoseDay*0.5

mean.round
#mean.round$round.min<-as.character(mean.round$round.min)
#mean.round$round.min
```

# Disease1

```{r}
Minutes_disease1<- ggplot(Disease1, aes(beaker, duration, fill=Arm)) + 
  MyTheme +
  scale_fill_brewer(palette = "Dark2")+
  scale_colour_brewer(palette = "Dark2")+
  scale_y_continuous(limits = c(20, 100),
                      expand = c(0.01, 0.01),
                      breaks = seq(0, 100, 10),
                      name="Seconds per beaker")+
  #  # scale_x_continuous(limits = c(0, 24),
  #                     expand = c(0.01, 0.01),
  #                     breaks = seq(0, 24, 2),
  #                     name="Time of the day")+
  geom_jitter(aes(colour=Arm), size=1, alpha=0.5)+
  stat_summary(fun.data = "mean_cl_boot", aes(fill=Arm), shape=21)
  # annotate(geom="text", x = 12, y = 1, parse=TRUE,
  #              label =paste0("Armand (min) ",mean.round$round.min[1], size=4))+
  #  annotate(geom="text", x = 36, y = 1, parse=TRUE,
  #              label =paste0("Armanda (min) ",mean.round$round.min[2], size=4))

#Minutes_round
Minutes_disease1 + facet_wrap(~Date)
```

# Disease2

```{r}
Minutes_disease2<- ggplot(Disease2, aes(beaker, duration/8, fill=Arm)) + 
  
  MyTheme +
  scale_fill_brewer(palette = "Dark2")+
  scale_colour_brewer(palette = "Dark2")+

  scale_y_continuous(limits = c(50, 76),
                      expand = c(0.01, 0.01),
                      breaks = seq(0, 100, 5),
                      name="Seconds per beaker")+
  # #  # scale_x_continuous(limits = c(0, 24),
  #                     expand = c(0.01, 0.01),
  #                     breaks = seq(0, 24, 2),
  #                     name="Time of the day")+
  geom_jitter(aes(colour=Arm), size=1, alpha=0.3)+
  stat_summary(fun.data = "mean_cl_boot", aes(fill=Arm), shape=21)
  # annotate(geom="text", x = 12, y = 1, parse=TRUE,
  #              label =paste0("Armand (min) ",mean.round$round.min[1], size=4))+
  #  annotate(geom="text", x = 36, y = 1, parse=TRUE,
  #              label =paste0("Armanda (min) ",mean.round$round.min[2], size=4))

#Minutes_round
Minutes_disease2 + facet_wrap(~Date)
#Minutes_disease2 

```


```{r, echo=FALSE}
mean.beaker2 <- ddply (Disease2, .(beaker, Arm, Date), summarise,
                D_mean = (mean (duration, na.rm = T))/8,
                D_sd = sd (duration, na.rm = T),
                number = n()*8)
mean.beaker2

mean.Arm2 <- ddply (Disease2, .(beaker, Arm),summarise,
                D_mean = (mean (duration, na.rm = T))/8,
                D_sd = sd (duration, na.rm = T),
                number = n()*8)
mean.Arm2

mean.day2 <- ddply (Disease2, .(Date, Arm),summarise,
                D_mean = (mean (duration, na.rm = T))/8,
                D_sd = sd (duration, na.rm = T),
                number = n()*8)
mean.day2

mean.round2 <- ddply (mean.Arm2, .(Arm),summarise,
                R_mean = mean (D_mean, na.rm = T),
                #R_sd = sd (D_mean, na.rm = T),
                number = n()*8)


mean.round2$round.min<-(round((mean.round2$R_mean*mean.round2$number)/60, 2))
mean.round2$DoseDay<-(24*60)/mean.round2$round.min
mean.round2$Vol.SW.day.mL<-mean.round2$DoseDay*60
mean.round2$Changes.SW.day.mL<-mean.round2$Vol.SW.day.mL/600
mean.round2$umol.NH.day.mL<-mean.round2$DoseDay*0.45
mean.round2$uM.NH.day.mL<-mean.round2$DoseDay*0.75

mean.round2

mean.round2$round.min<-as.character(mean.round2$round.min)
mean.round2$round.min

```

```{r}
Minutes_disease2b<- ggplot(Disease2, aes(Arm, duration/8, fill=Arm)) + 
  MyTheme +
  scale_fill_brewer(palette = "Dark2")+
  
  scale_y_continuous(limits = c(50, 76),
                      expand = c(0.01, 0.01),
                      breaks = seq(0, 80, 5),
                     name="Mean beaker duration (s)")+

  stat_summary(fun.data = "mean_cl_boot", aes(fill=Arm), shape=21)
  # annotate(geom="text", x = 1, y = 55, parse=TRUE,
  #               label = as.character(mean.round2$round.min[1]), size=4)+
  # annotate(geom="text", x = 2, y = 55, parse=TRUE,
  #            label = as.character(mean.round2$round.min[2]), size=4)

#Minutes_disease2b + facet_wrap(~Date)
#Minutes_disease2b
```


```{r}
Duration<-ggarrange(Minutes_nutrients+
                      theme(legend.position = "none"), 
                    Minutes_nutrientsb +  theme(legend.position = "none"),
                    Minutes_disease2 +
                       theme(legend.position = "none"), 
                    Minutes_disease2b+ theme(legend.position = "none"),
                     labels=c("Nutrients and Temperature ~ 2 weeks", "", 
                              "Nutrients, Temperature and Disease ~ 1 week"), 
                    ncol = 2, nrow=2, widths = c(3,0.9))
Duration

#ggsave(file="Outputs/Arm_stats.svg", plot=Duration, width=8, height=6)
```

```{r}
Stats.table<-rbind(mean.round, mean.round2)
#Stats.table
kable(as.data.frame(Stats.table, format = "markdown"), 
      longtable = TRUE, digits = 2)
#write.csv(Stats.table, "Outputs/Dosing regime.csv", row.names = F)
```

